name = "sharefrom"
main = "worker/index.ts"
compatibility_date = "2024-10-18"

[env.production]
routes = [
    { pattern = "sharefrom.xyz/*", zone_name = "sharefrom.xyz" }
]

# Serve static assets from dist directory
# Note: This creates an ASSETS binding automatically
[assets]
directory = "./dist"
binding = "ASSETS"

[[durable_objects.bindings]]
name = "SIGNALING_SERVER"
class_name = "SignalingServer"

[[migrations]]
tag = "v1"
new_classes = ["SignalingServer"]
